### ISSUE TITLE
documentation: debug ocrd-tool.json

### ISSUE THREAD

**Issue by tboenig** [OCR-D/ocrd_keraslm#12]
Please debug your ocrd_tool.json file. 
I found  an error:  
```xml
<report valid="false">
  <error>[tools.ocrd-keraslm-rate.parameters.model_file.content-type] 'application/x-hdf;subtype=bag' does not match '^[a-z0-9\\._-]+/[A-Za-z0-9\\._\\+-]+$'</error>
</report>
```
You can find the ocrd-tool.json documentation: https://ocr-d.github.io/ocrd_tool

Thank you very much.

**Comment by bertsky** [comment]
Another error in the validator. @kba, do you want me to open an issue in core? 

In fact, this was my attempt at solving the problem that there is no dedicated MIME type for HDF5 models (yet), but we have the obligation to state the MIME type so the framework knows we are dealing with a file reference here.

**Comment by kba** [comment]
> Another error in the validator. @kba, do you want me to open an issue in core?

I'll fix it. That regex restriction is pretty useless as-is.
